name: PassiveBCIHackathon2021
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - numpy=1.19
    - pandas=1.1
    - scikit-learn 
    - matplotlib
    - seaborn
    # - tensorflow-gpu
    - tensorflow
    - neptune-client
    - psutil
    # - catboost
    # - xgboost
    - notebook
    - pip
    - pip:
        # - pyriemann
        - mne
        - sktime
        - tsfresh